services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/stylesheet-pi.xsl:/etc/nginx/stylesheet-pi.xsl
      - ./html:/usr/share/nginx/html
      - ../input/examples:/usr/share/nginx/html/examples
